models/todo.py
from . import ModelMixin
from . import db


class Todo(db.Model, ModelMixin):
    __tablename__ = 'todos'
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(500))
    created_time = db.Column(db.Integer, default=0)
    tag = db.Column(db.String(500))
    #外键
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __init__(self, form):
        self.task = form.get('task', '')
        self.created_time = self.time()
        self.tag='unfinished'
    def valid(self):
        if len(self.task) == 0:
            return False
        else:
            return True

    def json(self):
        d = dict(
            id=self.id,
            task=self.task,
            created_time = self.created_time
        )
        return d

    def error_message(self):
        if len(self.task) <= 0:
            return 'todo不能输入为空'
        elif len(self.task) > 50:
            return '你的todo太长了'

routes/blog.py
from models.blog import Blog
from models.comment import Comment
from routes import *


main = Blueprint('blog', __name__)


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，无法使用博客')
        elif int(current_user().id) != int(1) :
            abort(401)
        return f(*args, **kwargs)

    return function


def admin_required_login(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，无法评论')
        return f(*args, **kwargs)

    return function


@main.route('/')
def index():
    u = current_user()
    blog_u = User.query.get(int(1))
    blog_list = blog_u.blogs
    return render_template('blog_index.html', blogs=blog_list, user=u)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    u = current_user()
    b = Blog(form)
    b.user = u
    if b.valid():
        b.save()
    # 蓝图中的 url_for 需要加上蓝图的名字，这里是 todo
    return redirect(url_for('.index'))




@main.route('/delete/<int:blog_id>')
@admin_required
def delete(blog_id):
    b = Blog.query.get(blog_id)
    b.delete()
    u = current_user()
    return redirect(url_for('.index'))


@main.route('/edit/<int:blog_id>')
@admin_required
def edit(blog_id):
    u = current_user()
    return render_template('blog_edit.html', blog_id=blog_id, user=u)


@main.route('/update', methods=['POST'])
def update():
    form = request.form
    u = current_user()
    b_id = form.get('blog_id', '')
    b = Blog.query.get(id=b_id)
    b.created_time = b.time()
    b.title = form.get('title', '')
    b.content = form.get('content','')
    if b.valid():
        b.save()
    return redirect(url_for('.index'))

@main.route('/cell/<int:blog_id>')
def cell(blog_id):
    u = current_user()
    blog = Blog.query.get(blog_id)
    return render_template('blog_cell.html', b=blog, user=u)


@main.route('/comment', methods=['POST'])
@admin_required_login
def comment():
    form = request.form

    bid = form.get('blog_id')
    b = Blog.query.get(bid)
    u = current_user()
    c = Comment(form)
    c.user = u
    c.blog = b
    b.comments_num = len(b.comments)
    if c.valid(w=b):
        c.save()
        b.comments_num = len(b.comments)
    return render_template('blog_cell.html', b=b, user=u)

routes/todo.py
from models.todo import Todo
from routes import *


main = Blueprint('todo', __name__)


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，无法操作todo')
        elif int(current_user().id) != int(1) :
            abort(401)
        return f(*args, **kwargs)
    return function



@main.route('/')
def all_todo():
    u = current_user()
    ftodos = Todo.query.filter_by(user_id=u.id, tag='finished').all()
    utodos = Todo.query.filter_by(user_id=u.id, tag='unfinished').all()
    return render_template('todo.html', utodos=utodos, ftodos=ftodos, user=u)


@main.route('/finished/<int:todo_id>')
@admin_required
def finished(todo_id):
    t = Todo.query.get(todo_id)
    t.tag = 'finished'
    return redirect(url_for('.all_todo'))


@main.route('/detele/<int:todo_id>')
@admin_required
def detele(todo_id):
    t = Todo.query.get(todo_id)
    t.detele()
    return redirect(url_for('.all_todo'))


@main.route('/edit/<int:todo_id>')
@admin_required
def edit(todo_id):
    u = current_user()
    return render_template('todo_edit.html', todo_id=todo_id, user=u)


@main.route('/update', methods=['post'])
@admin_required
def update():
    form = request.form
    tid = form.get('todo-id', -1)
    tcontent = form.get('content', '')
    t = Todo.query.get(tid)
    t.task = tcontent
    t.created_time = t.time()
    t.save()
    return redirect(url_for('.all_todo'))

routes/user.py
from models.user import User
from routes import *


main = Blueprint('user', __name__)


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，权限不足', user=current_user())

        return f(*args, **kwargs)

    return function


@main.route('/')
def index():
    if not User.query.get(int(1)):
        form1 = {
             'username': '管理员',
             'password': '123456',
             'avatar': '/static/img/ma.jpg'
        }
        u1 = User(form1)
        u1.id = int(1)
        u1.save()
    if not User.query.get(int(-1)):
        form2 = {
             'username': '游客',
             'avatar': '/static/img/nimy.jpg'
        }
        u2 = User(form2)
        u2.id = int(-1)
        u2.save()

    user = current_user()

    return render_template('one.html')
#

@main.route('/user_login')
def user_login():
    u = current_user()
    if int(u.id) > 0:
        return render_template('user_login.html', message='您已成功登录', user=u)
    else:
        return render_template('user_login.html', message='游客你好，请登录', user=u)


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    username = form.get('username','')
    user = User.query.filter_by(username=username).first()
    status, msg = user.validate_login(form)
    if status:
        session['user_id'] = user.id
        return render_template('user_login.html', message=msg, user=user)
    else:
        nimy = current_user()
        return render_template('user_login.html', message=msg, user=nimy)
#
@main.route('/register', methods=['POST'])
def register():
    form = request.form
    uu = current_user()
    u = User(form)
    status, msgs = u.valid()
    if status:
        u.save()
        message = msgs[0]
        return render_template('user_login.html', message=message, user=uu)
    else:
        message = msgs[1]
        return render_template('user_login.html', message=message, user=uu)


@main.route('/edit')
@admin_required
def edit():
    u = current_user()
    return render_template('user_update.html', user=u)



@main.route('/update', methods=['POST'])
@admin_required
def update():
    form = request.form
    u = current_user()
    asnew_user = User(form)
    status, msgs = asnew_user.update_valid(u)
    if status == True and len(msgs) == 1 :
        u.username = form.get('username', '')
        u.password = form.get('password', '')
        u.avatar = form.get('avatar', '/static/img/3.jpg')
        u.qq = form.get('qq', '他还没来的及输入他的QQ')
        u.email = form.get('email', '他还没来得及输入他的Email')
        u.sign = form.get('sign', '他还没有签名')
        u.save()
        message = '修改成功'
        return render_template('user_home.html', user=u, msssage=message)
    else:
        message = ';'.join(msgs[1:])
        return render_template('user_home.html', user=u, message=message)


@main.route('/home')
def home():
    u = current_user()
    return render_template('user_home.html', user=u, message='')

@main.route('/logout')
def logout():
    session['user_id'] = None
    u = current_user()
    return render_template('one.html')

routes/weibo.py
from models.weibo import Weibo
from models.comment import Comment
from routes import *


main = Blueprint('weibo', __name__)


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，无法使用博客')
        elif int(current_user().id) != int(1) :
            abort(401)
        return f(*args, **kwargs)

    return function


def admin_required_login(f):
    @wraps(f)
    def function(*args, **kwargs):
        if int(current_user().id) < 0:
            return render_template('user_login.html', message='您尚未登录，无法评论')
        return f(*args, **kwargs)

    return function




@main.route('/')
def index():
    u = current_user()
    weibo_u = User.query.get(int(1))
    weibo_list = weibo_u.weibos
    return render_template('weibo_index.html', weibos=weibo_list, user=u)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    u = current_user()
    t = Weibo(form)
    t.user = u
    if t.valid():
        t.save()
    return redirect(url_for('.index'))


@main.route('/comment', methods=['POST'])
@admin_required_login
def comment():
    form = request.form
    wid = form.get('weibo_id')
    w = Weibo.query.get(wid)
    u = current_user()
    c = Comment(form)
    c.user = u
    c.weibo_id = wid
    w.comments_num = len(w.comments)
    if c.valid(w):
        c.save()
        w.comments_num = len(w.comments)
    return redirect(url_for('.index'))


@main.route('/delete/<int:weibo_id>')
@admin_required
def delete(weibo_id):
    w = Weibo.query.get(weibo_id)
    w.delete()
    return redirect(url_for('.index'))


@main.route('/update', methods=['POST'])
@admin_required
def update():
    form = request.form
    u = current_user()
    wid = form.get('weibo_id', '')
    w = Weibo.query.get(id=wid)
    w.created_time = w.time()
    w.weibo = form.get('weibo','')
    if w.valid():
        w.save()
    return redirect(url_for('.index'))

templates/410.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/static/js/weibo.js"></script>
    <title>三千院和他的朋友们</title>
</head>
<body>
  <h1>用户名已存在！</h1>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Debug欢乐园</title>
    {% block head %}
    <link rel="stylesheet" href="/static/css/base.css">
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/api.js"></script>
    <!-- <script src="/static/js/base.js"></script> -->
    {% endblock %}
</head>
<body>
  <!-- 导航栏 -->
  <div class="base-div-have-head">
    <div class="base-div-head">
      {% if user.id > 0 %}
      <a class="base-a-head-logout"href="{{url_for('user.logout')}}">注销</a>
      {% endif %}
    {% block a %}
      <a class="base-span-head"href="{{url_for('user.index')}}">Debug欢乐园</a>
      <a class="base-a-head base-a-head-fontcolor"href="{{url_for('user.home')}}">Home</a>
      <a class="base-a-head base-a-head-fontcolor"href="{{url_for('user.user_login')}}">Login</a>
      <a class="base-a-head base-a-head-fontcolor"href="{{url_for('todo.all_todo')}}">Todo</a>
      <a class="base-a-head base-a-head-fontcolor"href="{{url_for('weibo.index')}}">Weibo</a>
      <a class="base-a-head base-a-head-fontcolor gua-active"href="/blog">Blog</a>
    {% endblock %}
    </div>
  </div>
    <!-- 导航栏下图片 -->
  <div class="base-div-head-img">
    <img id="base-id-head-img"src="{% block img %}{% endblock %}" alt="" />
  </div>

  <!-- 主内容（分左，右） -->
  <div class="base-div-have-content">
    <!-- 左内容 -->
    <div class="base-div-lift-content">
      {% block content %}{% endblock %}
    </div>
    <!-- 左边栏 -->
    <div class="base-div-have-right-content">
      <div class="base-div-right-content">
        <!-- <div class="base-div-right-content-avator">
          <img id="base-id-tmimg"src="/static/img/tt.jpg" alt="头像" />
        </div>
        <div class="base-div-right-content-tag">
          <p></p>
          <p>常用的掏粪工具：</p>
          <p>
            <li>Python&Flask</li>
            <li>JavaScript</li>
            <li>HTML</li>
            <li>CSS</li>
          </p>
          <p>276551515@qq.com</p>
          <p>如需要，请联系</p>
        </div> -->
        <div class="base-div-right-content-xxx">
          <div class="base-div-right-content-loginuser">

            <div class="base-div-right-content-loginuser-avatar">
              <a href="{{url_for('user.home')}}"><img height="150px"width="150px" src="{{user.avatar}}" alt="" /></a>
            </div>
            <div class="base-div-right-content-loginuser-name">
              你好：<a class="base-div-right-content-span base-div-right-content-span-username"href="{{url_for('user.home')}}">{{user.username}}</a>
              {% if user.id == -1 %}
                <a class="base-div-right-content-span base-div-right-content-span-username"href="{{url_for('user.user_login')}}">登录</a>
              {% endif %}
            </div>
            <div class="base-div-right-content-loginuser-qq">
              <img src="/static/img/qq.png" alt="" /> :<span base-div-right-content-span>{{user.qq}}</span>
            </div>
            <div class="base-div-right-content-loginuser-email">
              <img src="/static/img/email.png" alt="" /> :<span base-div-right-content-span>{{user.email}}</span>
            </div>
            <div class="base-div-right-content-loginuser-ll">
                说明：目前登录用户仅可评论与修改资料，后续功能博主正在卖力增加中......
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- 底栏 -->
  <div class="base-div-have-footer">
    <div class="base-div-footer">
      <div class="base-div-footer-a">
        <a class="base-a-footer"href="/blog">Blog</a>
        <a class="base-a-footer"href="/weibo">Weibo</a>
        <a class="base-a-footer"href="/todo">Todo</a>
        <a class="base-a-footer"href="{{url_for('user.user_login')}}">Login</a>
        <a class="base-a-footer"href="{{url_for('user.home')}}">Home</a>
      </div>
      <div class="base-div-footer-copyright">
        <p>Design by：chunguang.</p>
        <p>Thanks, GUA.</p>
      </div>
    </div>
  </div>

</body>
</html>

templates/blog_edit.html
{% extends "base.html" %}
{% block title %}编辑博客{% endblock %}
{% block head %}
  {{ super() }}
  <!-- <link rel="stylesheet" href="/static/css/pure-min.css">
  <link rel="stylesheet" href="/static/css/main.css">
  <script src="/static/js/weibo.js"></script> -->
{% endblock %}

{% block img %}/static/img/tm-blog-img.jpg{% endblock %}
{% block content %}
   <form class="" action={{url_for('.update')}} method="post">
     <input type="hidden" name="blog_id" value="{{ blog_id }}">
     <input type="text" name="title" placeholder="title">
     <textarea name="content" rows="8" cols="40" placeholder="内容"></textarea>
     <button type="submit" name="button">编辑完成</button>
   </form>
{% endblock %}
{% block right %}{% endblock %}

templates/todo_edit.html
{% extends "base.html" %}
{% block title %}todo{% endblock %}
{% block head %}
  {{ super() }}
  <script src="/static/js/todo.js"></script>
{% endblock %}
{% block a %}
  <a class="base-span-head">Debug欢乐园</a>
  <a class="base-a-head base-a-head-fontcolor"href="/">Registered</a>
  <a class="base-a-head base-a-head-fontcolor"href="/">Login</a>
  <a class="base-a-head base-a-head-fontcolor gua-active"href="/todo">Todo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/weibo">Weibo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/blog">Blog</a>
{% endblock %}
{% block img %}/static/img/tm-todo1-img.jpg{% endblock %}

{% block content %}
   <form class="" action="/todo/update" method="post">
     <input type="hidden" name="todo-id" value="{{ todo_id }}">
     <input type="text" name="content">
     <button type="submit" name="button">编辑完成</button>
   </form>
{% endblock %}
{% block right %}{% endblock %}

templates/user_home.html
{% extends "base.html" %}
{% block title %}home{% endblock %}
{% block head %}
  {{ super() }}
  <!-- <link rel="stylesheet" href="/static/css/pure-min.css">
  <link rel="stylesheet" href="/static/css/main.css">
  <script src="/static/js/weibo.js"></script> -->
  <style media="screen">
    .user-home {
      width: 80%;
      margin: 0 auto;
    }
    .user-home-san {
    padding: 20px;
    border-style: solid;
    border-width: 0px;
    border-color: #d4d2d2;
    border-bottom-width: 1px;
    }
    .user-home-img {
    padding: 0 0 30px 30px;
    background-color: #02564e;
    z-index: -10;
    border-style: solid;
    border-color: #d4d2d2;
    border-width: 3px;
    border-radius: 3px;
    }
    .avatar {
    position: relative;
    top: 80px;
    z-index: 100;
    border-style: solid;
    border-color: white;
    border-width: 5px;
    border-radius: 5px;
    }
    .span-username {
    margin-left: 20px;
    position: relative;
    top: 10px;
    font-size: 25px;
    color: white;
    }
    .span-sign {
    display: inline-block;
    padding: 12px;
    margin-left: 202px;
    color: #336699;
    font-size: 17px;
    }
    .span-qq {
    margin-left: 20px;
    color: #337dc2;
    font-style: italic;
    font-size: 17px;
    }
    .span-email {
    margin-left: 20px;
    color: #337dc2;
    font-style: italic;
    font-size: 17px;
    }
    .user-home-list {
      padding: 20px;
    }
    .user-home-qq {
      padding: 20px 0;
    }
    .user-home-email {
      padding: 20px 0;
    }
    .user-two-all {
      display: flex;
    }
    .user-home-list {
      flex-grow: 1;
      width: 50%;
    }
    .user-home-star-fans {
      flex-grow: 1;
      width: 50%;
    }
    .user-home-qq {
    margin-left: 20px;
    }
    .user-home-email {
    margin-left: 20px;
    }
    .user-home-star-fans {
    padding: 20px;
    }
    .user-home-star {
    padding: 20px 0;
    }
    .user-home-fans {
    padding: 20px 0;
    }
    .a-star-fans {
    text-decoration: inherit;
    color: #4681c5;
    font-size: 17px;
    font-style: oblique;
    }
    .user-have-san-a {
    text-align: right;
    padding: 22px;
    }
    .user-san-a {
    color: #F76333;
    font-size: 16px;
    border-style: solid;
    border-width: 1px;
    padding: 5px;
    text-decoration: inherit;
    border-radius: 3px;
    }
    .user-san-a:hover {
      background-color: #F76333;
      color: white;
    }

    .user-home-message {
      font-size: 17px;
      margin: 20px;
      text-align: center;
      color: #F76333;
    }
    .span-message {
    font-style: YouYuan;
    font-family: YouYuan;
    /* margin-top: 14px; */
    position: relative;
    top: 10px;
    font-size: 14px;
    color: white;
    }
  </style>
{% endblock %}
{% block a %}
  <a class="base-span-head"href="{{url_for('user.index')}}">Debug欢乐园</a>
  <a class="base-a-head base-a-head-fontcolor gua-active"href="{{url_for('user.home')}}">Home</a>
  <a class="base-a-head base-a-head-fontcolor"href="{{url_for('user.user_login')}}">Login</a>
  <a class="base-a-head base-a-head-fontcolor"href="/todo">Todo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/weibo">Weibo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/blog">Blog</a>
{% endblock %}
{% block img %}/static/img/tm-user2-img.jpg{% endblock %}
{% block content %}
    <div class="user-home">
      <div class="">

      </div>
      <div class="user-home-all">
        <div class="user-home-san">
          <div class="user-home-img">
            <img height="150px"width="150px"src="{{ user.avatar }}" class="avatar">
            <span class="span-username">{{ user.username }}</span>
            <span class="span-message"> , 放学别走 ！</span>
          </div>

          <span class="span-sign">{{ user.sign }}</span>
        </div>
      <div class="user-two-all">
        <div class="user-home-list">
          <div class="user-home-qq">
            <a href="#"><img src="/static/img/qq.png" alt="" /></a> :<span class="span-qq">{{ user.qq }}</span>
          </div>
          <div class="user-home-email">
            <a href="#"><img src="/static/img/email.png" alt="" /></a> :<span class="span-email">{{ user.email }}</span>
          </div>
        </div>
        <div class="user-home-star-fans">
          <div class="user-home-star">
            <a class="a-star-fans"href="#"><img src="/static/img/fans.png" alt="" />关注我的亲 ：</a>
            {% for f in user.asstars.fans %}
              <span class="fans-avatar">
                <a href="{{url_for('user.home', id=f.id)}}"><img height="24px"width="24px"src="{{avatar}}" alt="" /></a><img src="{{avatar}}" alt="" />
              </span>
            {% endfor %}
          </div>
          <div class="user-home-fans">
            <a class="a-star-fans"href="#"><img src="/static/img/xin.png" alt="" />我关注的人 ：</a>
            {% for s in user.asfans.star %}
              <span class="star-avatar">
                <a href="{{url_for('user.home', id=s.id)}}"><img height="24px"width="24px"src="{{avatar}}" alt="" /></a><img src="{{avatar}}" alt="" />
              </span>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="user-have-san-a">
        <a class="user-san-a"href="{{url_for('user.edit')}}">完善资料</a>
      </div>
      <div class="user-home-message">
        {{message}}
      </div>
    </div>
  </div>
{% endblock %}
{% block right %}{% endblock %}

templates/user_login.html
{% extends "base.html" %}
{% block title %}登录与注册{% endblock %}
{% block head %}
  {{ super() }}
  <!-- <link rel="stylesheet" href="/static/css/pure-min.css">
  <link rel="stylesheet" href="/static/css/main.css">
  <script src="/static/js/weibo.js"></script> -->
  <script type="text/javascript">
    $(document).ready(function(){
      $('#gua-login').on('click', function(){
        var alogin = $(this)
        var login = alogin.closest('.gua-right-content').find('.gua-have-form-login')
        var register = alogin.closest('.gua-right-content').find('.gua-have-form-register')
        var block = alogin.closest('.gua-right-content').find('.gua-block')
        login.removeClass('gua-hedden')
        register.addClass('gua-hedden')
        block.animate({"left": "92px"}, "fast")
        return false;
      })
    })

      $(document).ready(function(){
        $('#gua-register').on('click', function(){
          var aregister = $(this)
          var register = aregister.closest('.gua-right-content').find('.gua-have-form-register')
          var login = aregister.closest('.gua-right-content').find('.gua-have-form-login')
          var block = aregister.closest('.gua-right-content').find('.gua-block')
          register.removeClass('gua-hedden')
          login.addClass('gua-hedden')
          block.animate({"left": "168px"}, "fast")
          return false;

        })
      })
  </script>

  <style media="screen">
    .gua-right-content {
      width: 300px;
      margin: 0 auto;
    }

    .gua-form-login {

      margin: 0 auto;
      border: solid;
      border-width: 1px;
      border-color: #ded9d9;
      border-radius: 3px;
    }

    .gua-form-register {

      margin: 0 auto;
      border: solid;
      border-width: 1px;
      border-color: #ded9d9;
      border-radius: 3px;

    }
    .gua-input {
      width: 90%;
      height: 30px;
      padding: 5px;
      border: none;
      outline: none;

    }
    .gua-button {
      width: 92%;
      margin: 20px 0;
      background-color: #cc9900;
      color: white;
      border-radius: 3px;
    }

    .gua-have-input {
      text-align: center;

    }
    .gua-have-input + .gua-have-input {
      border-style: solid;
      border-color: #ded9d9;
      border-width: 0px;
      border-top-width: 1px;
    }

    .gua-have-h1 {
    text-align: center;
    margin-bottom: 20px;
    }
    .gua-a {
    margin: 15px;
    text-decoration: none;
    color: black;
    }

    .gua-block {
    height: 3px;
    width: 40px;
    background-color: #cc9900;
    position: relative;
    left: 92px;
  }
  .gua-message {
    color: red;
    font-size: 10px;
    text-align: center;

  }
  .gua-hedden {
    display: none;
  }
  </style>

{% endblock %}
{% block a %}
  <a class="base-span-head" href="{{url_for('user.index')}}">Debug欢乐园</a>
  <a class="base-a-head base-a-head-fontcolor"href="{{url_for('user.home')}}">Home</a>
  <a class="base-a-head base-a-head-fontcolor gua-active"href="{{url_for('user.user_login')}}">Login</a>
  <a class="base-a-head base-a-head-fontcolor"href="/todo">Todo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/weibo">Weibo</a>
  <a class="base-a-head base-a-head-fontcolor"href="/blog">Blog</a>
{% endblock %}
{% block img %}/static/img/tm-user2-img.jpg{% endblock %}
{% block content %}
  <div class="gua-right-content">
    <div class="gua-have-h1">
      <div class="gua-h1">
          <h2>Debug欢乐园</h2>
      </div>
      <div class="gua-h6">
          <h6>网站评论需要登录</h6>
      </div>
      <div>
        <a id="gua-login"class="gua-a"href="{{url_for('user.login')}}">登录</a>
        <a id="gua-register"class="gua-a"href="{{url_for('user.register')}}">注册</a>
        <div class="gua-block"></div>
      </div>
    </div>

    <div class="gua-have-form-login">


      <form class="" action="{{url_for('user.login')}}" method="post">
        <div class="gua-form-login">
          <div class="gua-have-input">
            <input class="gua-input"type="text" name="username" value="" placeholder="用户名"><br>
          </div>
          <div class="gua-have-input">
            <input class="gua-input"type="password" name="password" value="" placeholder="密码"><br>
          </div>
        </div>
        <div class="gua-have-input">
          <button class="gua-button gua-input"type="submit" name="button">登录</button>
        </div>
      </form>

    </div>

    <div class="gua-have-form-register gua-hedden">
      <form class="" action="{{url_for('user.register')}}" method="post">
        <div class="gua-form-register">
          <div class="gua-have-input">
            <input class="gua-input"type="text" name="username" value="" placeholder="用户名必须大于等于5位"><br>
          </div>
          <div class="gua-have-input">
            <input class="gua-input"type="text" name="password" value="" placeholder="密码必须大于等于5位"><br>
          </div>
          <div class="gua-have-input">
            <input class="gua-input"type="text" name="captcha" value="" placeholder="请输入验证码 '吃瓜群众' "><br>
          </div>
        </div>
        <div class="gua-have-input">
          <button class="gua-button gua-input"type="submit" name="button">注册</button>
        </div>
      </form>

    </div>

    <div class="gua-message">
      {{message}}
    </div>

  </div>
{% endblock %}
{% block right %}{% endblock %}